version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux fix
    environment:
      DB_HOST: mysql  # Connect to mysql service directly
      DB_USER: root
      DB_PASS: root
      DB_NAME: adatok
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adatok
    volumes:
      - mysql_data:/var/lib/mysql
      - ./adatok.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: