version: '3.8'
services:
  php:
    build: .
    ports:
      - "10000:10000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adatok
    ports:
      - "3306:3306"