services:
  - type: web
    name: php-app
    dockerfile: Dockerfile
    dockerContext: .
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_USER
        value: root
      - key: DB_PASS
        fromService:
          type: postgres  # Note: Render converts MySQL to Postgres
          name: db
          property: connectionString
    numInstances: 1

  - type: postgres  # Render converts MySQL to Postgres automatically
    name: db
    databaseName: adatok
    user: root
    plan: free