services:
  - type: web
    name: php-app
    dockerfile: Dockerfile
    envVars:
      - key: DB_HOST
        value: ${DB_INTERNAL_HOST}  # Will be provided by Render
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASS
        value: ${DB_PASSWORD}
      - key: DB_NAME
        value: adatok
    numInstances: 1

databases:
  - name: mysqldb
    databaseName: adatok
    user: root
    plan: free
    technology: mysql