services:
  - type: web
    name: php-app
    dockerfile: Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: mysqldb
          property: host
      - key: DB_USER
        fromDatabase:
          name: mysqldb
          property: user
      - key: DB_PASS
        fromDatabase:
          name: mysqldb
          property: password
      - key: DB_NAME
        value: adatok
    numInstances: 1

databases:
  - name: mysqldb
    databaseName: adatok
    plan: free
    technology: mysql